from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from . import ast_nodes as ast


TYPE_MAP = {
    "poora": "int",
    "dasha": "float",
    "akshar": "char",
    "shabd": "char*",
    "khaali": "void",
}


OP_MAP = {
    "aur": "&&",
    "ya": "||",
    "nahi": "!",
}


def generate_c(program: ast.Program) -> str:
    gen = CCodeGenerator()
    return gen.generate(program)


@dataclass
class CCodeGenerator:
    indent_width: int = 4

    def __post_init__(self) -> None:
        self._lines: List[str] = []
        self._indent = 0

    def generate(self, program: ast.Program) -> str:
        self._lines = []
        self._indent = 0

        self._emit("// Auto-generated by HingC Compiler")
        self._emit("#include <stdio.h>")
        self._emit("#include <stdlib.h>")
        self._emit("#include <string.h>")
        self._emit("")

        functions = [s for s in program.body if isinstance(s, ast.FunctionDecl)]
        main_stmts = [s for s in program.body if not isinstance(s, ast.FunctionDecl)]

        for fn in functions:
            self._emit_function(fn)
            self._emit("")

        self._emit("int main() {")
        self._indent += 1
        for st in main_stmts:
            self._emit_stmt(st)
        self._emit("return 0;")
        self._indent -= 1
        self._emit("}")

        return "\n".join(self._lines) + "\n"

    # -------------------------
    # emit helpers
    # -------------------------

    def _emit(self, line: str) -> None:
        if line and not line.startswith("#") and not line.startswith("//"):
            self._lines.append(" " * (self._indent * self.indent_width) + line)
        else:
            # keep preprocessor + file header unindented
            self._lines.append(line)

    def _ctype(self, hing_type: str) -> str:
        return TYPE_MAP.get(hing_type, hing_type)

    def _c_op(self, op: str) -> str:
        return OP_MAP.get(op, op)

    def _c_string(self, s: str) -> str:
        # Escape for C string literal; input is the decoded token value.
        out = []
        for ch in s:
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\t":
                out.append("\\t")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\0":
                out.append("\\0")
            else:
                out.append(ch)
        return '"' + "".join(out) + '"'

    def _c_char(self, c: str) -> str:
        if c == "'":
            return "'\\''"
        if c == "\\":
            return "'\\\\'"
        if c == "\n":
            return "'\\n'"
        if c == "\t":
            return "'\\t'"
        if c == "\r":
            return "'\\r'"
        if c == "\0":
            return "'\\0'"
        return f"'{c}'"

    # -------------------------
    # functions / statements
    # -------------------------

    def _emit_function(self, fn: ast.FunctionDecl) -> None:
        ret = self._ctype(fn.return_type)
        params = ", ".join(f"{self._ctype(t)} {n}" for t, n in fn.params)
        self._emit(f"{ret} {fn.name}({params}) {{")
        self._indent += 1
        for st in fn.body.statements:
            self._emit_stmt(st)
        self._indent -= 1
        self._emit("}")

    def _emit_stmt(self, st: ast.Statement) -> None:
        if isinstance(st, ast.Block):
            self._emit("{")
            self._indent += 1
            for s in st.statements:
                self._emit_stmt(s)
            self._indent -= 1
            self._emit("}")
            return

        if isinstance(st, ast.VarDeclaration):
            ctype = self._ctype(st.type)
            if st.value is None:
                self._emit(f"{ctype} {st.name};")
            else:
                self._emit(f"{ctype} {st.name} = {self._emit_expr(st.value)};")
            return

        if isinstance(st, ast.Assignment):
            self._emit(f"{st.name} = {self._emit_expr(st.value)};")
            return

        if isinstance(st, ast.IfStatement):
            self._emit(f"if ({self._emit_expr(st.condition)}) " + "{")
            self._indent += 1
            for s in st.then_body.statements:
                self._emit_stmt(s)
            self._indent -= 1
            self._emit("}")
            for cond, body in st.elif_clauses:
                self._emit(f"else if ({self._emit_expr(cond)}) " + "{")
                self._indent += 1
                for s in body.statements:
                    self._emit_stmt(s)
                self._indent -= 1
                self._emit("}")
            if st.else_body is not None:
                self._emit("else {")
                self._indent += 1
                for s in st.else_body.statements:
                    self._emit_stmt(s)
                self._indent -= 1
                self._emit("}")
            return

        if isinstance(st, ast.WhileStatement):
            self._emit(f"while ({self._emit_expr(st.condition)}) " + "{")
            self._indent += 1
            for s in st.body.statements:
                self._emit_stmt(s)
            self._indent -= 1
            self._emit("}")
            return

        if isinstance(st, ast.ForStatement):
            init = self._emit_stmt_inline(st.init)
            cond = self._emit_expr(st.condition) if st.condition is not None else ""
            upd = self._emit_stmt_inline(st.update)
            self._emit(f"for ({init}; {cond}; {upd}) " + "{")
            self._indent += 1
            for s in st.body.statements:
                self._emit_stmt(s)
            self._indent -= 1
            self._emit("}")
            return

        if isinstance(st, ast.ReturnStatement):
            if st.value is None:
                self._emit("return;")
            else:
                self._emit(f"return {self._emit_expr(st.value)};")
            return

        if isinstance(st, ast.PrintStatement):
            fmt = self._emit_expr(st.format_str)
            args = ", ".join(self._emit_expr(a) for a in st.args)
            if args:
                self._emit(f"printf({fmt}, {args});")
            else:
                self._emit(f"printf({fmt});")
            return

        if isinstance(st, ast.InputStatement):
            fmt = self._emit_expr(st.format_str)
            vars_ = ", ".join(self._emit_expr(v) for v in st.variables)
            if vars_:
                self._emit(f"scanf({fmt}, {vars_});")
            else:
                self._emit(f"scanf({fmt});")
            return

        if isinstance(st, ast.BreakStatement):
            self._emit("break;")
            return

        if isinstance(st, ast.ContinueStatement):
            self._emit("continue;")
            return

        if isinstance(st, ast.SwitchStatement):
            self._emit(f"switch ({self._emit_expr(st.expr)}) " + "{")
            self._indent += 1
            for c in st.cases:
                self._emit(f"case {self._emit_expr(c.value)}:")
                self._indent += 1
                for s in c.body.statements:
                    self._emit_stmt(s)
                self._indent -= 1
            if st.default is not None:
                self._emit("default:")
                self._indent += 1
                for s in st.default.statements:
                    self._emit_stmt(s)
                self._indent -= 1
            self._indent -= 1
            self._emit("}")
            return

        if isinstance(st, ast.ExpressionStatement):
            self._emit(f"{self._emit_expr(st.expr)};")
            return

        if isinstance(st, ast.FunctionDecl):
            # already emitted above main()
            return

        raise TypeError(f"Unsupported statement node: {st.__class__.__name__}")

    def _emit_stmt_inline(self, st: Optional[ast.Statement]) -> str:
        if st is None:
            return ""
        if isinstance(st, ast.VarDeclaration):
            ctype = self._ctype(st.type)
            if st.value is None:
                return f"{ctype} {st.name}"
            return f"{ctype} {st.name} = {self._emit_expr(st.value)}"
        if isinstance(st, ast.Assignment):
            return f"{st.name} = {self._emit_expr(st.value)}"
        if isinstance(st, ast.ExpressionStatement):
            return self._emit_expr(st.expr)
        raise TypeError(f"Unsupported for-loop clause: {st.__class__.__name__}")

    # -------------------------
    # expressions
    # -------------------------

    def _emit_expr(self, e: Optional[ast.Expression]) -> str:
        if e is None:
            return ""
        if isinstance(e, ast.IntLiteral):
            return str(e.value)
        if isinstance(e, ast.FloatLiteral):
            # keep as-is; Python may print 3.0 which is fine in C
            return repr(e.value)
        if isinstance(e, ast.StringLiteral):
            return self._c_string(e.value)
        if isinstance(e, ast.CharLiteral):
            return self._c_char(e.value)
        if isinstance(e, ast.Identifier):
            return e.name
        if isinstance(e, ast.FunctionCall):
            args = ", ".join(self._emit_expr(a) for a in e.args)
            return f"{e.name}({args})"
        if isinstance(e, ast.UnaryOp):
            op = self._c_op(e.op)
            return f"({op}{self._emit_expr(e.operand)})"
        if isinstance(e, ast.BinaryOp):
            op = self._c_op(e.op)
            return f"({self._emit_expr(e.left)} {op} {self._emit_expr(e.right)})"
        raise TypeError(f"Unsupported expression node: {e.__class__.__name__}")

