import os
import subprocess
import tempfile
from pathlib import Path
import shutil

import pytest

from hingc.compiler.codegen import generate_c
from hingc.compiler.parser import parse


def test_hello_world_output_c_contains_printf():
    ast = parse('shuru\nlikho("Hello\\n")\nkhatam\n')
    c = generate_c(ast)
    assert "// Auto-generated by HingC Compiler" in c
    assert "#include <stdio.h>" in c
    assert "printf(" in c
    assert "int main()" in c


def test_if_else_generates_correct_c_keywords():
    src = """shuru
rakho poora x = 10
agar (x > 5) {
  likho("Bada\\n")
} warna {
  likho("Chota\\n")
}
khatam
"""
    c = generate_c(parse(src))
    assert "if (" in c
    assert "else {" in c


def test_function_generates_above_main():
    src = """shuru
kaam poora jodo(poora a, poora b) {
  wapas a + b
}
rakho poora x = jodo(1, 2)
likho("%d\\n", x)
khatam
"""
    c = generate_c(parse(src))
    assert "int jodo(int a, int b)" in c
    assert c.index("int jodo") < c.index("int main")


def test_for_loop_generates_correct_c():
    src = """shuru
karo (rakho poora i = 0 ; i < 3 ; i = i + 1) {
  likho("%d\\n", i)
}
khatam
"""
    c = generate_c(parse(src))
    assert "for (" in c
    assert "int i = 0" in c


@pytest.mark.skipif(shutil.which("gcc") is None, reason="gcc not available on PATH")
def test_generated_c_compiles_with_gcc():
    ast = parse('shuru\nlikho("Hi\\n")\nkhatam\n')
    c = generate_c(ast)
    with tempfile.TemporaryDirectory() as td:
        cpath = Path(td) / "out.c"
        exe = Path(td) / ("out.exe" if os.name == "nt" else "out")
        cpath.write_text(c, encoding="utf-8")
        res = subprocess.run(
            ["gcc", str(cpath), "-o", str(exe)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        assert res.returncode == 0, res.stderr


@pytest.mark.skipif(shutil.which("gcc") is None, reason="gcc not available on PATH")
def test_generated_c_output_matches_expected():
    ast = parse('shuru\nlikho("Namaste\\n")\nkhatam\n')
    c = generate_c(ast)
    with tempfile.TemporaryDirectory() as td:
        cpath = Path(td) / "out.c"
        exe = Path(td) / ("out.exe" if os.name == "nt" else "out")
        cpath.write_text(c, encoding="utf-8")
        subprocess.check_call(["gcc", str(cpath), "-o", str(exe)])
        try:
            run = subprocess.run([str(exe)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        except OSError as e:
            msg = str(e).lower()
            if "blocked" in msg or "policy" in msg:
                pytest.skip(f"Execution blocked by OS policy: {e}")
            raise
        assert run.stdout.replace("\r\n", "\n") == "Namaste\n"

